/*!
** @file   ObjDict.c
** @author CAN Festival -- NNP
** @date   OD File produced: 2011-03-06 21:48:07.869000
**
** @brief This file is generated by the NNP Tool -- Object Dictionary Editor, as
** originally developed by CAN Festival and modified by the NNP Team.
** Specific contents are detailed in Object Dictionary Template.
** Editor modification: 4/29/2010 -- rev 1.0.0
**
** This ObjDict.c file is generated by hand - jeu
**
*/

/*This object dictionary file should only be modified by the Object Dictionary Editor */

#include "ObjDict.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

UNS8 clockRate = 0x0;				/* Mapped at index 0x2000, subindex 0x00 */
UNS8 Control_ScriptStatus = 0x0;	/* Mapped at index 0x2001, subindex 0x01 */
UNS8 Control_CurrentGroup = 0x0;	/* Mapped at index 0x2001, subindex 0x02 */
UNS8 X_Network = 0x0;				/* Mapped at index 0x2002, subindex 0x00 */
UNS16 Temperature = 0x0;			/* Mapped at index 0x2003, subindex 0x00 */
UNS8 TemperatureIMU[2] =
{ 0x00,  0x00 };
UNS8 Status_modeSelect = 0x0;		/* Mapped at index 0x2010, subindex 0x01 */
UNS8 Status_numTPDO = 1;			/* Mapped at index 0x2010, subindex 0x02 */
UNS8 Status_numRPDO = 1;			/* Mapped at index 0x2010, subindex 0x03 */
UNS8 Status_channelSelect = 0x0;	/* Mapped at index 0x2010, subindex 0x04 */
UNS8 Status_profileSelect = 0x0;	/* Mapped at index 0x2010, subindex 0x05 */
UNS8 Status_profileWrite = 0x0;		/* Mapped at index 0x2010, subindex 0x06 */
UNS8 Status_NodeId = 0x73;
UNS16 Status_TestValue = 0x00;
UNS16 Status_NodeTest = 0;
UNS8 Accelerometers[4] =
{ 0x00,  0x00,  0x00, 0x00 };		/* Mapped at index 0x2011, subindex 0x00 */
UNS8 AccelerometersFiltered[4] =
{ 0x00,  0x00,  0x00, 0x00 };       /* Mapped at index 0x2011, subindex 0x01 */
INTEGER8 AccelerometersTilt[4] =
{ 0x00,  0x00,  0x00, 0x00 };       /* Mapped at index 0x2011, subindex 0x02 */
UNS8 Gyroscopes[6] =
{ 0x00,  0x00,  0x00, 0x00,  0x00, 0x00 };
UNS8 Quaternion[16] =
{ 0x00,  0x00,  0x00, 0x00,  0x00, 0x00,  0x00,  0x00,\
  0x00,  0x00,  0x00, 0x00,  0x00, 0x00,  0x00,  0x00 };
UNS8 AccelerometerSettings = 0;  	/* Mapped at index 0x2012, subindex 0x01 */
UNS32 AddressRequest = 0x00000000;
UNS8 memorySelect = 0x00;
UNS8 triggerReadMemory = 0x00;
UNS8 writeByteMemory = 0x00;
UNS8 statusByteMemory = 0x00;
UNS8 ReadMemoryData[36] =
{ 0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00,\
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00,  0x00,  0x00,  0x00, \
  0x00,  0x00,  0x00, 0x00, 0x00,  0x00,  0x00, 0x00,  0x00 , 0x00,  0x00,  0x00 };
UNS16 addressCounter = 0x0000;
UNS16 CAN_FormErrors = 0x00;
UNS16 CAN_StuffErrors = 0x00;
UNS16 CAN_BitErrors = 0x00;
UNS16 CAN_OtherErrors = 0x00;
UNS16 CAN_TotalErrors = 0x00;
UNS16 CAN_Rx_ErrCounter = 0x00;
UNS16 CAN_Tx_ErrCounter = 0x00;
UNS16 CAN_Receive_BEI = 0x00;
UNS16 CAN_Receive_Messages = 0x00;
UNS16 CAN_Transmit_Messages = 0x00;
UNS16 CAN_Interrupts_Off = 0x00;
UNS8 DiagnosticsEnabled = 0x01;
UNS8 Diagnostic_VIN = 0x00;
UNS8 Diagnostic_VIC = 0x00;
UNS8 Diagnostic_VOS = 0x00;
UNS8 Diagnostic_VDD = 0x00;

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 ObjDict_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 ObjDict_bDeviceNodeId = 0x73;

/**************************************************************************/
/* Array of message processing information */

const UNS8 ObjDict_iam_a_slave = 1;

TIMER_HANDLE ObjDict_heartBeatTimers[1];

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 ObjDict_obj1000 = 0x53504E4E;	/* 1397771854 */
                    const subindex ObjDict_Index1000[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1000 }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 ObjDict_obj1001 = 0x0;	/* 0 */
                    const subindex ObjDict_Index1001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1001 }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 ObjDict_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1003[] =
                    {
                      0x0	/* 0 */
                    };
                    ODCallback_t ObjDict_Index1003_callbacks[] =
                     {
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index1003[] =
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1003 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1003[0] }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 ObjDict_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 ObjDict_obj1006 = 0xFF;	/* 0 */
                    const subindex ObjDict_Index1006[] =
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1006 }
                     };


/* index 0x1008 :   Manufacturer Device Name. */
                    INTEGER8 ObjDict_obj1008[25] = "Generic NNP Remote Module";
                    const subindex ObjDict_Index1008[] =
                     {
                       { RO, visible_string, 25, (void*)&ObjDict_obj1008 }
                     };

/* index 0x1014 :   Emergency COB ID */
                    UNS32 ObjDict_obj1014 = 0x80 + 0x02;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time */
                    UNS8 ObjDict_highestSubIndex_obj1016 = 0;
                    UNS32 ObjDict_obj1016[]={0};

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 ObjDict_obj1017 = 2311;	/*  - 2.3 sec prime update*/
                    ODCallback_t ObjDict_Index1017_callbacks[] =
                     {
                       NULL,
                     };
                    const subindex ObjDict_Index1017[] =
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1017 }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 ObjDict_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    INTEGER8 ObjDict_obj1018_Vendor_ID[10] = "NNPS";
                    UNS8 ObjDict_obj1018_Product_Code = 0x4;
                    UNS32 ObjDict_obj1018_Revision_Number = APP_REV;
                    UNS32 ObjDict_obj1018_Serial_Number = 0x0000;	/* 152592 */
                    const subindex ObjDict_Index1018[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1018 },
                       { RO, visible_string, 10, (void*)&ObjDict_obj1018_Vendor_ID },
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_obj1018_Product_Code },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Revision_Number },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1018_Serial_Number }
                     };

/* index 0x1200 :   Server SDO Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1200 = 2; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO = 0x602;	/* 1538 */
                    UNS32 ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO = 0x582;	/* 1410 */
                    const subindex ObjDict_Index1200[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1200 },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Client_to_Server_Receive_SDO },
                       { RO, uint32, sizeof (UNS32), (void*)&ObjDict_obj1200_COB_ID_Server_to_Client_Transmit_SDO }
                     };

/* index 0x1400 :   Receive PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1400 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1400_Source_Address = 0x0;	/* 387 */
                    UNS8 ObjDict_obj1400_Transmission_Type = 0xFF;	/* 255 */
                    UNS16 ObjDict_obj1400_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1400_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1400_Event_Timer = 0x0;	/* 0 */
                    const subindex ObjDict_Index1400[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1400 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1400_Source_Address },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1400_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1400_Event_Timer }
                     };


/* index 0x1600 :   Receive PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1600 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1600[] =
                    {
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00	/* 0 */
                    };
                    subindex ObjDict_Index1600[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1600 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1600[7] }
                     };


/* index 0x1800 :   Transmit PDO 1 Parameter. */
                    UNS8 ObjDict_highestSubIndex_obj1800 = 5; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1800_COB_ID_used_by_PDO = 0x182;	/* use 0x80000182 to disable PDO */
                    UNS8 ObjDict_obj1800_Transmission_Type = 0xFD;	/* use 0xFD to disable */
                    UNS16 ObjDict_obj1800_Inhibit_Time = 0x0;	/* 0 */
                    UNS8 ObjDict_obj1800_Compatibility_Entry = 0x0;	/* 0 */
                    UNS16 ObjDict_obj1800_Event_Timer = 0x0;	/* 0 */
                    ODCallback_t ObjDict_Index1800_callbacks[] =
                     {
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                       NULL,
                     };
                    subindex ObjDict_Index1800[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1800 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1800_COB_ID_used_by_PDO },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Transmission_Type },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Inhibit_Time },
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_obj1800_Compatibility_Entry },
                       { RW, uint16, sizeof (UNS16), (void*)&ObjDict_obj1800_Event_Timer }
                     };


/* index 0x1A00 :   Transmit PDO 1 Mapping. */
                    UNS8 ObjDict_highestSubIndex_obj1A00 = 8; /* number of subindex - 1*/
                    UNS32 ObjDict_obj1A00[] =
                    {
                      0x00,     /* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00,	/* 0 */
                      0x00	/* 0 */
                    };
                    const subindex ObjDict_Index1A00[] =
                     {
                       { RW, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj1A00 },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[0] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[1] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[2] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[3] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[4] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[5] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[6] },
                       { RW, uint32, sizeof (UNS32), (void*)&ObjDict_obj1A00[7] }
                     };


/* index 0x2000 :   Mapped variable Clock */
                    UNS8 ObjDict_highestSubIndex_obj2000 = 1; /* number of subindex - 1*/
                    ODCallback_t Clock_callbacks[] =
                     {
                       NULL,
                       NULL,
                     };
                    const subindex ObjDict_Index2000[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2000 },
                       { RW, uint8, sizeof (UNS8), (void*)&clockRate }
                     };

/* index 0x2001 :   Mapped variable Control */
                    UNS8 ObjDict_highestSubIndex_obj2001 = 2; /* number of subindex - 1*/
                    const subindex ObjDict_Index2001[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2001 },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_ScriptStatus },
                       { RW, uint8, sizeof (UNS8), (void*)&Control_CurrentGroup },
                     };

/* index 0x2002 :   Mapped variable X-Network */
                    UNS8 ObjDict_highestSubIndex_obj2002 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2002[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2002 },
                       { RW, uint8, sizeof (UNS8), (void*)&X_Network }
                     };

/* index 0x2003 :   Mapped variable Temperature */
                    UNS8 ObjDict_highestSubIndex_obj2003 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2003[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2003 },
                       { RO, uint16, sizeof (UNS16), (void*)&Temperature }
                     };



/* index 0x2010 :   Mapped variable Status */
                    UNS8 ObjDict_highestSubIndex_obj2010 = 9; /* number of subindex - 1*/
                    const subindex ObjDict_Index2010[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2010 },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_modeSelect },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numTPDO },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_numRPDO },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_channelSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileSelect },
                       { RW, uint8, sizeof (UNS8), (void*)&Status_profileWrite },
                       { RO, uint8, sizeof (UNS8), (void*)&Status_NodeId },
                       { RW, uint16, sizeof (UNS16), (void*)&Status_TestValue },
                       { RW, uint16, sizeof (UNS16), (void*)&Status_NodeTest }

                     };

/* index 0x2011 :   Mapped variable Accelerometer Values */
                    UNS8 ObjDict_highestSubIndex_obj2011 = 4; /* number of subindex - 1*/
                    const subindex ObjDict_Index2011[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2011 },
                       { RW, uint8, 4, (void*)&Accelerometers[0] },
                       { RW, uint8, 4, (void*) &AccelerometersFiltered[0] },
                       { RW, int8, 4, (void*) &AccelerometersTilt[0] },
                       { RO, uint8, 16, (void*) &Quaternion[0] }
                     };

/* index 0x2012 :   Mapped variable Accelerometer Settings */
                    UNS8 ObjDict_highestSubIndex_obj2012 = 1; /* number of subindex - 1*/
                    const subindex ObjDict_Index2012[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2012 },
                       { RW, uint8, sizeof (UNS8), (void*) &AccelerometerSettings }
                     };


/* index 0x2020 :   Mapped variable RecordTransfer */
                    UNS8 ObjDict_highestSubIndex_obj2020 = 7;
                    const subindex ObjDict_Index2020[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2020 },
                       { RW, uint32, sizeof (UNS32), (void*)&AddressRequest },    // 1
                       { RW, uint8, 36, (void*)&ReadMemoryData[0] },              // 19
                       { RW, uint32, sizeof (UNS32), (void*)&addressCounter },    // 21
                       { RW, uint8, sizeof (UNS8), (void*)&memorySelect },
                       { RW, uint8, sizeof (UNS8), (void*)&triggerReadMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&writeByteMemory },
                       { RW, uint8, sizeof (UNS8), (void*)&statusByteMemory }

                     };

/* index 0x2500 :   Mapped variable CAN */
                    UNS8 ObjDict_highestSubIndex_obj2500 = 11; /* number of subindex - 1*/
                    const subindex ObjDict_Index2500[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2500 },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_TotalErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_BitErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_StuffErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_FormErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_OtherErrors },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Rx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Tx_ErrCounter },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_BEI },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Receive_Messages },
                       { RO, uint16, sizeof (UNS16), (void*)&CAN_Transmit_Messages },
                       { RO, uint16, sizeof (UNS16),  (void*)&CAN_Interrupts_Off }
                     };

/* index 0x2900 :   Mapped variable RestoreList */
                    UNS8 ObjDict_highestSubIndex_obj2900 = 1; /* number of subindex - 1*/
                    UNS16 RestoreList[RESTORE_COUNT] =  { 0x1400, /*RPDO Params(10)*/ \
														  0x1600, /*RPDO Mapping(32)*/ \
														  0x1800, /*TPDO Params(10)*/ \
														  0x1A00, /*TPDO Mapping(32)*/ \
														  0x2001, /*Control(4)*/\
														  0x2012, /*Accelerometer Settings*/};

                    const subindex ObjDict_Index2900[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj2900 },
                       { RO, uint16, sizeof(RestoreList), (void*)&RestoreList[0] }
                     };

/* index 0x3000 :   Mapped variable Diagnostics */
                    UNS8 ObjDict_highestSubIndex_obj3000 = 5; /* number of subindex - 1*/
                    const subindex ObjDict_Index3000[] =
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&ObjDict_highestSubIndex_obj3000 },
                       { RW, uint8, sizeof (UNS8), (void*)&DiagnosticsEnabled },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIN },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VIC },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VOS },
                       { RO, uint8, sizeof (UNS8), (void*)&Diagnostic_VDD }
                     };

/**************************************************************************/
/* Declaration of variables                                       */
/**************************************************************************/

const indextable ObjDict_objdict[] =
{
  { (subindex*)ObjDict_Index1000,sizeof(ObjDict_Index1000)/sizeof(ObjDict_Index1000[0]), 0x1000},
  { (subindex*)ObjDict_Index1001,sizeof(ObjDict_Index1001)/sizeof(ObjDict_Index1001[0]), 0x1001},
  { (subindex*)ObjDict_Index1006,sizeof(ObjDict_Index1006)/sizeof(ObjDict_Index1006[0]), 0x1006},
  { (subindex*)ObjDict_Index1008,sizeof(ObjDict_Index1008)/sizeof(ObjDict_Index1008[0]), 0x1008},
  { (subindex*)ObjDict_Index1017,sizeof(ObjDict_Index1017)/sizeof(ObjDict_Index1017[0]), 0x1017},
  { (subindex*)ObjDict_Index1018,sizeof(ObjDict_Index1018)/sizeof(ObjDict_Index1018[0]), 0x1018},
  { (subindex*)ObjDict_Index1200,sizeof(ObjDict_Index1200)/sizeof(ObjDict_Index1200[0]), 0x1200},
  { (subindex*)ObjDict_Index1400,sizeof(ObjDict_Index1400)/sizeof(ObjDict_Index1400[0]), 0x1400},
  { (subindex*)ObjDict_Index1600,sizeof(ObjDict_Index1600)/sizeof(ObjDict_Index1600[0]), 0x1600},
  { (subindex*)ObjDict_Index1800,sizeof(ObjDict_Index1800)/sizeof(ObjDict_Index1800[0]), 0x1800},
  { (subindex*)ObjDict_Index1A00,sizeof(ObjDict_Index1A00)/sizeof(ObjDict_Index1A00[0]), 0x1A00},
  { (subindex*)ObjDict_Index2000,sizeof(ObjDict_Index2000)/sizeof(ObjDict_Index2000[0]), 0x2000},
  { (subindex*)ObjDict_Index2001,sizeof(ObjDict_Index2001)/sizeof(ObjDict_Index2001[0]), 0x2001},
  { (subindex*)ObjDict_Index2002,sizeof(ObjDict_Index2002)/sizeof(ObjDict_Index2002[0]), 0x2002},
  { (subindex*)ObjDict_Index2003,sizeof(ObjDict_Index2003)/sizeof(ObjDict_Index2003[0]), 0x2003},
  { (subindex*)ObjDict_Index2010,sizeof(ObjDict_Index2010)/sizeof(ObjDict_Index2010[0]), 0x2010},
  { (subindex*)ObjDict_Index2011,sizeof(ObjDict_Index2011)/sizeof(ObjDict_Index2011[0]), 0x2011},
  { (subindex*)ObjDict_Index2012,sizeof(ObjDict_Index2012)/sizeof(ObjDict_Index2012[0]), 0x2012},
  { (subindex*)ObjDict_Index2020,sizeof(ObjDict_Index2020)/sizeof(ObjDict_Index2020[0]), 0x2020},
  { (subindex*)ObjDict_Index2500,sizeof(ObjDict_Index2500)/sizeof(ObjDict_Index2500[0]), 0x2500},
  { (subindex*)ObjDict_Index2900,sizeof(ObjDict_Index2900)/sizeof(ObjDict_Index2900[0]), 0x2900},
  { (subindex*)ObjDict_Index3000,sizeof(ObjDict_Index3000)/sizeof(ObjDict_Index3000[0]), 0x3000}
};

const indextable * ObjDict_scanIndexOD (UNS16 wIndex, UNS32 * errorCode, ODCallback_t **callbacks)
{
	int i;
	*callbacks = NULL;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
        case 0x1006: i = 2;break;
		case 0x1008: i = 3;break;
		case 0x1017: i = 4;*callbacks = ObjDict_Index1017_callbacks; break;
		case 0x1018: i = 5;break;
		case 0x1200: i = 6;break;
		case 0x1400: i = 7;break;
		case 0x1600: i = 8;break;
		case 0x1800: i = 9;*callbacks = ObjDict_Index1800_callbacks; break;
		case 0x1A00: i = 10;break;
		case 0x2000: i = 11;break;
		case 0x2001: i = 12;break;
		case 0x2002: i = 13;break;
		case 0x2003: i = 14;break;
		case 0x2010: i = 15;break;
		case 0x2011: i = 16;break;
        case 0x2012: i = 17;break;
        case 0x2020: i = 18;break;
        case 0x2500: i = 19;break;
        case 0x2900: i = 20;break;
        case 0x3000: i = 21;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &ObjDict_objdict[i];
}

/*
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
//Should match number of TPDOs!
s_PDO_status ObjDict_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index ObjDict_firstIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  9, /* PDO_TRS */
  10 /* PDO_TRS_MAP */
};

const quick_index ObjDict_lastIndex = {
  6, /* SDO_SVR */
  0, /* SDO_CLT */
  7, /* PDO_RCV */
  8, /* PDO_RCV_MAP */
  9, /* PDO_TRS */
  10 /* PDO_TRS_MAP */
};

const UNS16 ObjDict_ObjdictSize = sizeof(ObjDict_objdict)/sizeof(ObjDict_objdict[0]);

CO_Data ObjDict_Data = CANOPEN_NODE_DATA_INITIALIZER(ObjDict);
